name: coverity-scan
on:
  schedule:
    - cron: '0 0 * * SAT'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        id: jdk-11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Get coverity cli
        run: |
          wget https://scan.coverity.com/download/linux64 --no-verbose --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=jeremylong%2FDependencyCheck" -O coverity_tool.tgz
          mkdir coverity_tool
          tar xzf coverity_tool.tgz --strip 1 -C coverity_tool
      - name: Perform coverity scan
        run: |
          export PATH=`pwd`/coverity_tool/bin:$PATH
          cov-build --dir cov-int mvn -DskipTests=true package --no-transfer-progress --batch-mode
      - name: Submit coverity scan
        run: |
          tar czvf scan.tgz cov-int
          curl --form token=${{ secrets.COVERITY_TOKEN }} \
               --form email=jeremy.long@gmail.com \
               --form file=@scan.tgz \
               --form version="main" \
               --form description="Weekly Scan" \
               https://scan.coverity.com/builds?project=jeremylong%2FDependencyCheck
